Configurations:
- AddsDomain

AddsDomain:
  DomainFqdn: '[x={ $Datum.Global.Domain.DomainFqdn }=]'
  DomainName: '[x={ $Datum.Global.Domain.DomainFqdn }=]'
  DomainAdministrator: '[x={ $Datum.Global.Domain.DomainJoinCredentials }=]'
  SafeModeAdministratorPassword: '[x={ $Datum.Global.Domain.DomainJoinCredentials }=]'
  DatabasePath: C:\Windows\NTDS
  LogPath: C:\Windows\Logs
  SysvolPath: C:\Windows\SYSVOL
  ForestMode: WinThreshold
  ForceRebootBefore: True

DscTagging:
  Layers:
    - '[x={ Get-DatumSourceFile -Path $File } =]'
