@{
    PSDependOptions              = @{
        AddToPath  = $true
        Target     = 'output\RequiredModules'
        Parameters = @{
            Repository      = 'PSGallery'
            AllowPreRelease = $true
        }
    }

    'powershell-yaml'            = '0.4.7'
    InvokeBuild                  = '5.10.3'
    PSScriptAnalyzer             = '1.21.0'
    Pester                       = '5.4.0'
    Plaster                      = '1.1.4'
    ModuleBuilder                = '2.0.0'
    ChangelogManagement          = '3.0.1'
    Sampler                      = '0.116.2'
    'Sampler.GitHubTasks'        = '0.3.5-preview0002'
    'Sampler.AzureDevOpsTasks'   = '0.1.2'
    PowerShellForGitHub          = '0.16.1'
    'Sampler.DscPipeline'        = '0.2.0-preview0015'
    MarkdownLinkCheck            = '0.2.0'
    'DscResource.AnalyzerRules'  = '0.2.0'
    DscBuildHelpers              = '0.2.1'
    Datum                        = '0.40.1-preview0001'
    ProtectedData                = '4.1.3'
    'Datum.ProtectedData'        = '0.0.1'
    'Datum.InvokeCommand'        = '0.3.0'
    ReverseDSC                   = '2.0.0.14'
    Configuration                = '1.5.1'
    Metadata                     = '1.5.7'
    xDscResourceDesigner         = '1.13.0.0'
    'DscResource.Test'           = '0.16.1'
    'DscResource.DocGenerator'   = '0.11.2'

    # Composites
    'CommonTasks'                 = '0.10.0-preview0006'

    #DSC Resources
    xPSDesiredStateConfiguration = '9.1.0'
    ComputerManagementDsc        = '8.5.0'
    NetworkingDsc                = '9.0.0'
    JeaDsc                       = '0.7.2'
    XmlContentDsc                = '0.0.1'
    WebAdministrationDsc         = '4.1.0'
    SecurityPolicyDsc            = '2.10.0.0'
    StorageDsc                   = '5.0.1'
    Chocolatey                   = '0.0.79'
    ActiveDirectoryDsc           = '6.2.0'
    DfsDsc                       = '4.4.0.0'
    WdsDsc                       = '0.11.0'
    xDhcpServer                  = '3.1.0'
    xDscDiagnostics              = '2.8.0'
    DnsServerDsc                 = '3.0.0'
    FailoverClusterDsc           = '2.1.0'
    GPRegistryPolicyDsc          = '1.2.0'
    AuditPolicyDsc               = '1.4.0.0'
    SharePointDSC                = '4.8.0'
    xExchange                    = '1.33.0'
    SqlServerDsc                 = '16.1.0-preview0009'
    UpdateServicesDsc            = '1.2.1'
    xWindowsEventForwarding      = '1.0.0.0'
    OfficeOnlineServerDsc        = '1.5.0'
    xBitlocker                   = '1.4.0.0'
    ActiveDirectoryCSDsc         = '5.0.0'
    HyperVDsc                    = '4.0.0-preview0005'
    DSCR_PowerPlan               = '1.3.0'
    FileSystemDsc                = '1.1.1'
    PackageManagement            = '1.4.8.1'
    PowerShellGet                = '2.2.5'
    ConfigMgrCBDsc               = '3.0.0'
    MmaDsc                       = '1.3.0'
    CertificateDsc               = '5.1.0'
    xRobocopy                    = '2.0.0.0'
    VSTSAgent                    = '2.0.14'
    FileContentDsc               = '1.3.0.151'
    xRemoteDesktopSessionHost    = '2.1.1-preview0001'
    cScom                        = '1.0.4'
    AzureConnectedMachineDsc     = '1.4.0'

}
